# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Category

# Model Form Field configuration
form: $/elon/catalog/models/category/fields.yaml

# Model Class name
modelClass: Elon\Catalog\Models\Category

# Default redirect location
defaultRedirect: elon/catalog/categories

# Create page
create:
    title: Create Category
    redirect: elon/catalog/categories/update/:id
    redirectClose: elon/catalog/categories

# Update page
update:
    title: Edit Category
    redirect: elon/catalog/categories
    redirectClose: elon/catalog/categories

# Preview page
preview:
    title: Preview Category