# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Product Image

# Model Form Field configuration
form: $/elon/catalog/models/productimage/fields.yaml

# Model Class name
modelClass: Elon\Catalog\Models\ProductImage

# Default redirect location
defaultRedirect: elon/catalog/productimages

# Create page
create:
    title: Create Product Image
    redirect: elon/catalog/productimages/update/:id
    redirectClose: elon/catalog/productimages

# Update page
update:
    title: Edit Product Image
    redirect: elon/catalog/productimages
    redirectClose: elon/catalog/productimages

# Preview page
preview:
    title: Preview Product Image