# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Tag

# Model Form Field configuration
form: $/elon/catalog/models/tag/fields.yaml

# Model Class name
modelClass: Elon\Catalog\Models\Tag

# Default redirect location
defaultRedirect: elon/catalog/tags

# Create page
create:
    title: Create Tag
    redirect: elon/catalog/tags/update/:id
    redirectClose: elon/catalog/tags

# Update page
update:
    title: Edit Tag
    redirect: elon/catalog/tags
    redirectClose: elon/catalog/tags

# Preview page
preview:
    title: Preview Tag